version: '2'

services:
  my-db:
    image: mysql/mysql-server:5.7
    expose: 
      - 3306
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=pass
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "./db-data:/var/lib/mysql"
  web:
    build: .
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ".:/code"
    depends_on:
      - my-db
    command: python manage.py runserver 0.0.0.0:8000
      
